# fly.toml app configuration file generated for hifi-app-strapi on 2024-04-05T13:46:14+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hifi-app-strapi'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 1337
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[mounts]
  source = "data"
  destination = "/opt/app/public/uploads"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

